swagger: "2.0"
info:
  version: 1.0.0
  title: rocket-service
  description: My cool TypeScript app
basePath: /api/v1

consumes:
  - application/json
produces:
  - application/json


definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress
  UserBody:
    title: user
    required:
      - name
      - password
    properties:
      name:
        type: string
        example: zhangshan
      password:
        type: string
        example: "123456"
paths:
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples

  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the example to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
  
  /users:
    get:
      tags: 
        - Users
      description: Fetch all Users
      responses:
        200:
          description: Returns all users
    post:
      tags: 
        - Users
      description: Creates a new user
      operationId: addUser
      parameters:
        - name: user
          in: body
          description: add a user
          required: true
          schema: 
            $ref: "#/definitions/UserBody"
      responses:
        200:
          description: Return all users